name: Build & Push Docker image to GHCR

on:
  push:
    branches: [ main ]  # passe ggf. den Branch an
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract image name
        id: meta
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/telegram-bot
          echo "image=$IMAGE_NAME" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.image }}:latest
